version: "3"
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - "./client:/app"
    ports:
      - "4000:4000"
    depends_on:
      - server
  server:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - "./server:/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    restart: always
    ports:
      - 27017:27017
  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports:
      - "9100:9090"
    volumes:
      - ./promotheus:/etc/promotheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  mongodb_data:
  grafana-data:
  prometheus_data:
