global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "portfolie2"
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets:
        - "prometheus:9090"
        - "idonotexists:564"
