global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "promotheus"
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: "server"
    static_configs:
      - targets: 
        - localhost:80

      #- job_name: 'grafana'
      #   static_configs:
      #  -targets: ['docker.for.win.localhost:3001']
