global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: 'portfolie2'
  honor_labels: true
  static_configs:
  - targets: ['docker.for.win.localhost:8080']
    static_configs:
      -targets: ['docker.for.win.localhost:8080']
  - job_name: 'grafana'

    static_configs: 
      -targets: ['docker.for.win.localhost:3001']
      
